[package]
name = "gzinspector"
authors = ["Jason Grey <jason@jason-grey.com>"]
edition = "2018"
version = "0.1.0"

[dependencies]
flate2 = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.0", features = ["derive"] }
chrono = "0.4"
crc32fast = "1.3"