
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release Binary
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Release Binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Create Release Archive
        run: |
          cd target/release
          tar czf ../../gzinspector-linux-x86_64.tar.gz gzinspector
          cd ../..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: gzinspector-linux-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}